<?php
$z[0]=Array("field","",109,135);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",143,171);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",180,209);
$z[2][4]['name']="typename";
$z[3]=Array("field","",211,240);
$z[3][4]['name']="typename";
$z[4]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> ",327,456);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>