<?php
$z[0]=Array("global","",129,155);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",303,329);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channelartlist","\r\n              <li class=\"menu2\" onmouseover=\"this.className='menu1'\" onmouseout=\"this.className='menu2'\"> <span> <a class=\"{dede:field.currentstyle/}\" href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></span>\r\n                <div class=\"list\">\r\n                  <div class=\"listt\"> {dede:channel type='son' noself='yes'} <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> {/dede:channel} </div>\r\n                </div>\r\n              </li>\r\n              ",586,1205);
$z[2][4]['typeid']="top";
$z[2][4]['currentstyle']="current";

?>